angular.module('gettext').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100 */
    gettextCatalog.setStrings('cs', {});
    gettextCatalog.setStrings('da', {});
    gettextCatalog.setStrings('de', {"Average: {{home.data[1]}}":"Durchschnitt: {{home.data[1]}}","Cancel":"Abbrechen","Choose Player to deal {{subject}} with:":"Team wählen um Deal {{subject}} zu vereinbaren:","Choose type of deal:":"Wählen Sie Art des Deals:","Confirm":"Bestätigen","Correct: {{home.correctAnswer}}":"Richtig: {{home.correctAnswer}}","Do you want to deal {{subject}} with":"Möchten sie Deal {{subject}} abschließen mit","EUROPE":"EUROPA","New deal":"Neuer Deal","Next":"Nächster","Please rate a team! Give {{score}} point!":"Bitte bewerten Sie ein Team! Geben Sie {{score}} Punkte!","Point given!":"Punkt vergeben!","Rank: {{status.player.rank}}":"Rang: {{status.player.rank}}","Score: {{status.player.score}}":"Punkte: {{status.player.score}}","This deal does not exist!":"Diesen Deal gibt es nicht!","This deal is ACTIVE.":"Dieser Deal ist AKTIV.","This deal was DENIED.":"Dieser Deal wurde abgelehnt.","Total: {{home.data[0]}}":"Gesamt: {{home.data[0]}}","VOTE":"ABSTIMMUNG","Waiting for reply...":"Warten auf Antwort ...","You are not joined in the game!":"Nicht dem Spiel beigetreten!","You are voting for:":"Sie stimmen für:","Your choice is sent!":"Ihre Stimme wurde abgeschickt!","Your voting weight depends on your rank!":"Das Stimmgewicht hängt vom aktuellen Rang ab!","should get {{score}} points from you?":"soll {{score}} Punkte von Dir bekommen?","with team {{deal.player1Id}}":"mit Team {{deal.player1Id}}"});
    gettextCatalog.setStrings('en', {"Average: {{home.data[1]}}":"Average: {{home.data[1]}}","Cancel":"Cancel","Choose Player to deal {{subject}} with:":"Choose Player to deal {{subject}} with:","Choose type of deal:":"Choose type of deal:","Confirm":"Confirm","Correct: {{home.correctAnswer}}":"Correct: {{home.correctAnswer}}","Do you want to deal {{subject}} with":"Do you want to deal {{subject}} with","EUROPE":"EUROPE","New deal":"New deal","Next":"Next","Please rate a team! Give {{score}} point!":"Please rate a team! Give {{score}} point!","Point given!":"Point given!","Rank: {{status.player.rank}}":"Rank: {{status.player.rank}}","Score: {{status.player.score}}":"Score: {{status.player.score}}","This deal does not exist!":"This deal does not exist!","This deal is ACTIVE.":"This deal is ACTIVE.","This deal was DENIED.":"This deal was DENIED.","Total: {{home.data[0]}}":"Total: {{home.data[0]}}","VOTE":"VOTE","Waiting for reply...":"Waiting for reply...","You are not joined in the game!":"You are not joined in the game!","You are voting for:":"You are voting for:","Your choice is sent!":"Your choice is sent!","Your voting weight depends on your rank!":"Your voting weight depends on your rank!","should get {{score}} points from you?":"should get {{score}} points from you?","with team {{deal.player1Id}}":"with team {{deal.player1Id}}"});
    gettextCatalog.setStrings('fr', {});
    gettextCatalog.setStrings('nl', {});
    gettextCatalog.setStrings('no', {});
    gettextCatalog.setStrings('pl', {});
    gettextCatalog.setStrings('pt', {});
/* jshint +W100 */
}]);