angular.module('gettext').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100 */
    gettextCatalog.setStrings('cs', {});
    gettextCatalog.setStrings('da', {});
    gettextCatalog.setStrings('de', {"Average: {{home.data[1]}}":"Durchschnitt: {{home.data[1]}}","Cancel":"Abbruch","Choose Player to deal {{subject}} with:":"Choose Player tgo deal {{subject}} with:","Choose type of deal:":"Art des Deals aussuchen:","Confirm":"Bestätigen","Correct: {{home.correctAnswer}}":"Richtige Antwort: {{home.correctAnswer}}","Do you want to deal {{subject}} with":"Möchtest du {{subject}} dealen mit","EUROPE":"EUROPA","New deal":"Neuer Deal","Next":"Weiter","Please rate a team! Give {{score}} point!":"Bitte ein Team bewerten! {{score}} Punkte vergeben!","Point given!":"Punkt wurde vergeben!","Rank: {{status.player.rank}}":"Rang: {{status.player.rank}}","Score: {{status.player.score}}":"Punkte: {{status.player.score}}","This deal does not exist!":"Dieser Deal existiert nicht!","This deal is ACTIVE.":"Dieser Deal ist AKTIV!","This deal was DENIED.":"Dieser Deal wurde abgelehnt.","Total: {{home.data[0]}}":"Gesamt: {{home.data[0]}}","VOTE":"Abstimmung","Waiting for reply...":"Warte auf Antwort...","You are not joined in the game!":"Du bist dem Spiel nicht beigetreten!","You are voting for:":"Du stimmst für:","Your choice is sent!":"Deine Stimme wurde abgeschickt!","Your voting weight depends on your rank!":"Das Stimmgewicht hängt von Deiner Position ab!","should get {{score}} points from you?":"sollte {{score}} Punkte von dir erhalten?","with team {{deal.player1Id}}":"mit Team {{deal.player1Id}}"});
    gettextCatalog.setStrings('en', {"Average: {{home.data[1]}}":"Average: {{home.data[1]}}","Cancel":"Cancel","Choose Player to deal {{subject}} with:":"Choose Player to deal {{subject}} with:","Choose type of deal:":"Choose type of deal:","Confirm":"Confirm","Correct: {{home.correctAnswer}}":"Correct: {{home.correctAnswer}}","Do you want to deal {{subject}} with":"Do you want to deal {{subject}} with","EUROPE":"EUROPE","New deal":"New deal","Next":"Next","Please rate a team! Give {{score}} point!":"Please rate a team! Give {{score}} point!","Point given!":"Point given!","Rank: {{status.player.rank}}":"Rank: {{status.player.rank}}","Score: {{status.player.score}}":"Score: {{status.player.score}}","This deal does not exist!":"This deal does not exist!","This deal is ACTIVE.":"This deal is ACTIVE.","This deal was DENIED.":"This deal was DENIED.","Total: {{home.data[0]}}":"Total: {{home.data[0]}}","VOTE":"VOTE","Waiting for reply...":"Waiting for reply...","You are not joined in the game!":"You are not joined in the game!","You are voting for:":"You are voting for:","Your choice is sent!":"Your choice is sent!","Your voting weight depends on your rank!":"Your voting weight depends on your rank!","should get {{score}} points from you?":"should get {{score}} points from you?","with team {{deal.player1Id}}":"with team {{deal.player1Id}}"});
    gettextCatalog.setStrings('fr', {});
    gettextCatalog.setStrings('nl', {});
    gettextCatalog.setStrings('no', {});
    gettextCatalog.setStrings('pl', {});
    gettextCatalog.setStrings('pt', {});
/* jshint +W100 */
}]);