angular.module('gettext').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100 */
    gettextCatalog.setStrings('de', {"Czech":"Tschechisch","Danish":"Dänisch","Dutch":"Niederländisch","English":"Englisch","French":"Französisch","German":"Deutsch","Language":"Sprache","Norwegian":"Norwegisch","Polish":"Polnisch","Portuguese":"Portugiesisch"});
    gettextCatalog.setStrings('en', {"Czech":"Czech","Danish":"Danish","Dutch":"Dutch","English":"English","French":"French","German":"German","Language":"Language","Norwegian":"Norwegian","Polish":"Polish","Portuguese":"Portuguese"});
    gettextCatalog.setStrings('cs', {});
    gettextCatalog.setStrings('da', {});
    gettextCatalog.setStrings('de', {"Add new item":"Neuen Eintrag hinzufügen","CONNECT DB":"VERBINDE DATENBANK","Cancel":"Abbrechen","Current deck:":"Ausgewählter Strang:","Current step:":"Aktueller Eintrag:","Default mapping:":"Voreingestellte Gerätezuordnung:"});
    gettextCatalog.setStrings('en', {"ALARM":"ALARM","Action":"Action","Add new item":"Add new item","Auto-Go:":"Auto-Go:","BACK":"BACK","CONNECT DB":"CONNECT DB","Cancel":"Cancel","Change score":"Change score","Choose target where item will be appended.":"Choose target where item will be appended.","Color":"Color","Color:":"Color:","Comment":"Comment","Configuration":"Configuration","Configuration option:":"Configuration option:","Content":"Content","Copy":"Copy","Correct":"Correct","Cost:":"Cost:","Current deck:":"Current deck:","Current step:":"Current step:","Deck":"Deck","Decks and items":"Decks and items","Default mapping:":"Default mapping:","Delete":"Delete","Delete deck":"Delete deck","Description:":"Description:","Device Manager":"Device Manager","Direct item":"Direct item","Display:":"Display:","Duplicate deck":"Duplicate deck","Export CSV":"Export CSV","GO":"GO","GO 2":"GO 2","GOTO":"GOTO","Game stopped":"Game stopped","Import":"Import","Import JSON":"Import JSON","Import:":"Import:","Interfaces":"Interfaces","Joined":"Joined","Language:":"Language:","Load":"Load","Log":"Log","Mapped:":"Mapped:","Max. steps:":"Max. steps:","Memory":"Memory","Move":"Move","Move item":"Move item","New deck":"New deck","New option":"New option","New title:":"New title:","No.":"No.","OS Info for {{osInfo.hostname}}":"OS Info for {{osInfo.hostname}}","Option":"Option","Option:":"Option:","Options:":"Options:","Playback":"Playback","Process":"Process","RASPI Control":"RASPI Control","REBOOT":"REBOOT","REGO":"REGO","RELOAD":"RELOAD","REPAIR DB":"REPAIR DB","RESTART":"RESTART","RESTART SERVER":"RESTART SERVER","RESTART WI-FI":"RESTART WI-FI","Rank":"Rank","Rating:":"Rating:","Required votes:":"Required votes:","SHUTDOWN":"SHUTDOWN","Save":"Save","Score":"Score","Score:":"Score:","Source:":"Source:","System":"System","Team ID":"Team ID","Teams":"Teams","Text:":"Text:","Time until decision:":"Time until decision:","Time:":"Time:","Title:":"Title:","Total duration: {{getTimeForDeck()}}":"Total duration: {{getTimeForDeck()}}","Trigger":"Trigger","Type":"Type","Type:":"Type:","Uptime":"Uptime","VOTE":"VOTE","Value =":"Value =","Vote count:":"Vote count:","Wi-Fi name:":"Wi-Fi name:","Wi-Fi password":"Wi-Fi password","Win:":"Win:","With rating:":"With rating:"});
    gettextCatalog.setStrings('fr', {});
    gettextCatalog.setStrings('nl', {});
    gettextCatalog.setStrings('no', {});
    gettextCatalog.setStrings('pl', {});
    gettextCatalog.setStrings('pt', {});
/* jshint +W100 */
}]);